# Generated by Django 3.0 on 2019-12-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='tag',
            field=models.CharField(max_length=10, unique=True, verbose_name='tag to recognize the role easily'),
        ),
    ]
