# Generated by Django 3.0 on 2019-12-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191212_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Role Name'),
        ),
    ]
