# Generated by Django 3.0 on 2019-12-12 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='authorized_at',
            field=models.DateTimeField(null=True, verbose_name='When the request is authorized'),
        ),
        migrations.AlterField(
            model_name='request',
            name='authorized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorizer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='inspected_at',
            field=models.DateTimeField(null=True, verbose_name='When the request is accepted'),
        ),
        migrations.AlterField(
            model_name='request',
            name='inspected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('ESTADO_1', 'Estado 1'), ('ESTADO_2', 'Estado 2')], max_length=20, verbose_name='State of the request'),
        ),
        migrations.DeleteModel(
            name='RequestState',
        ),
    ]
