# Generated by Django 3.0 on 2019-12-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20191212_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Automatically setted'),
        ),
    ]
